# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: "Mohamed Fathi Abdallah"
author: "Mohamed Fathi Abdallah"
description: "Mohamed Fathi Abdallah ©2024"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
icon: # the emoji used as the favicon
mathjax: true
url: "http://www.mfathiabdallah.com" # the base hostname & protocol for your site

# Layout
show_social: true 
show_excerpts: false      # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: true            # use a dark header

# Menu

navigation:        # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV & Publications", file: "publications.md"}
  - {title: "More About Me", file: "more_about_me.md"}
  - {title: "News & Views", file: "blogs.md"}
  - {title: "Contact", file: "contact.md"}
  

external:          # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mohamed.fathi@ugent.be"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/MoFathiAbdallah"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/mohamed-fathi-abdallah-66126a38/"}
  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Mohamed-Abdallah-13"}
  - {title: GoogleScholar, icon: user-graduate, url: "https://scholar.google.com/citations?user=05FfukgAAAAJ&hl=en"}
  - {title: Orcid, icon: orcid, url: "https://orcid.org/0000-0002-3903-6452"}
  - {title: Ghent University, icon: landmark, url: "https://www.ugent.be/"}

 #- {title: Github, icon: github, url: "https://github.com/mfathiabdallah"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-github-metadata
  - jekyll-imagemagick
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-twitter-plugin
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-toc
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-last-modified-at
  - jekyll-compose
  - jekyll-tagging
  - jekyll-redirect-to
  - jekyll-polyglot
  - jekyll-lunr-js-search
  - jekyll-asset-path-plugin
  - jekyll-ga
  - jekyll-optional-front-matter
  - jekyll-cloudinary

# Additional Configurations

# 404 Page
permalink: /404.html

# Google Analytics
google_analytics: UA-XXXXX-X

# Search Configuration (Replace with your Algolia API keys)
#algolia:
#  application_id: your_application_id
#  index_name: your_index_name

# Asset Optimization (Add more options as needed)
asset_optimization:
  css:
    minify: true
    inline: true
  js:
    minify: true
    inline: false

# Content Security Policy (CSP)
#csp: "default-src 'self'; script-src 'self' https://www.google-analytics.com;"

# Accessibility Improvements
#accessibility:
#  aria_landmarks: true
#  keyboard_navigation: true
#  semantic_markup: true

# Structured Data Markup
#structured_data:
#  organization:
#    name: Your Organization
#    url: https://www.example.com
#    logo: https://www.example.com/logo.png

# Performance Monitoring (Add more tools as needed)
#performance_monitoring:
#  lighthouse: true
#  pagespeed_insights: true
